FROM inclusivedesign/centos

RUN yum install sudo -y

# Disable requiretty in /etc/sudoers, found at https://gist.github.com/petems/367f8119bbff011bf83e
# If we don't do this, Ansible is unable to use sudo within the localhost context
RUN echo "Removing requiretty" \
    && sed -i "s/^.*requiretty/#Defaults requiretty/" /etc/sudoers \
    && echo "Complete!"

RUN yum install ansible -y
